'use client'
import { useEffect, useState } from 'react'
import { CMS_URL, CMS_KEY, CMS_ADMINS } from '@/lib/cms-config'

type Session={access_token:string,user:{email?:string}}
const defaults:any={
  'home.hero':{title:'El sentido de la vida se encuentra sirviendo a la vida',subtitle:'Espiritualidad, conciencia y transformación interior. Una invitación a reconocer aquello que ya somos.'},
  'sobre.maria':{title:'La vida es un despertar',image:'/images/maria-sobre-bn.png'},
  'contacto':{email:'olid.maria@gmail.com',whatsapp:'620430048'},
}
async function req(path:string,init:any={}){const r=await fetch(CMS_URL+path,{...init,headers:{apikey:CMS_KEY,'Content-Type':'application/json',...(init.headers||{})}});if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json()}
export default function Admin(){
 const [session,setSession]=useState<Session|null>(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[msg,setMsg]=useState(''),[items,setItems]=useState<any>(defaults),[tab,setTab]=useState('contenido')
 useEffect(()=>{const s=localStorage.getItem('maria_admin_session');if(s)setSession(JSON.parse(s))},[])
 useEffect(()=>{if(session)load()},[session])
 async function login(signup=false){try{setMsg('');if(!CMS_ADMINS.includes(email.toLowerCase()))throw new Error('Este correo no está autorizado.');const p=signup?'/auth/v1/signup':'/auth/v1/token?grant_type=password';const d=await req(p,{method:'POST',body:JSON.stringify({email,password})});if(!d.access_token){setMsg('Cuenta creada. Si Supabase pide confirmar el correo, confirma el mensaje recibido y luego inicia sesión.');return}localStorage.setItem('maria_admin_session',JSON.stringify(d));setSession(d)}catch(e:any){setMsg(e.message)}}
 async function load(){try{const d=await req('/rest/v1/site_content?select=key,value',{headers:{Authorization:`Bearer ${session!.access_token}`}});const next={...defaults};d.forEach((x:any)=>next[x.key]=x.value);setItems(next)}catch(e:any){setMsg(e.message)}}
 async function save(key:string){try{await req('/rest/v1/site_content?on_conflict=key',{method:'POST',headers:{Authorization:`Bearer ${session!.access_token}`,Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({key,value:items[key]})});setMsg('Guardado correctamente. La web pública puede tardar unos segundos en reflejar el cambio.')}catch(e:any){setMsg(e.message)}}
 async function upload(file:File){try{const safe=Date.now()+'-'+file.name.replace(/[^a-zA-Z0-9._-]/g,'-');const r=await fetch(`${CMS_URL}/storage/v1/object/site-media/${safe}`,{method:'POST',headers:{apikey:CMS_KEY,Authorization:`Bearer ${session!.access_token}`,'Content-Type':file.type},body:file});if(!r.ok)throw new Error(await r.text());const url=`${CMS_URL}/storage/v1/object/public/site-media/${safe}`;await navigator.clipboard.writeText(url);setMsg('Imagen subida. Su URL se copió al portapapeles: '+url)}catch(e:any){setMsg(e.message)}}
 if(!session)return <main className="min-h-screen bg-[#f6f3ee] px-5 py-20"><div className="mx-auto max-w-md rounded-xl bg-white p-8 shadow-xl"><h1 className="font-serif text-3xl">Gestión · El Despertar</h1><p className="mt-2 text-sm text-black/60">Panel privado. No está enlazado desde la web pública.</p><input className="mt-8 w-full rounded border p-3" placeholder="Correo autorizado" value={email} onChange={e=>setEmail(e.target.value)}/><input className="mt-3 w-full rounded border p-3" type="password" placeholder="Contraseña" value={password} onChange={e=>setPassword(e.target.value)}/><button onClick={()=>login(false)} className="mt-5 w-full rounded bg-black p-3 text-white">Entrar</button><button onClick={()=>login(true)} className="mt-3 w-full rounded border p-3">Crear mi acceso por primera vez</button>{msg&&<p className="mt-4 text-sm">{msg}</p>}</div></main>
 const edit=(key:string,field:string,label:string)=><label className="block"><span className="mb-1 block text-sm font-semibold">{label}</span><textarea className="min-h-24 w-full rounded border p-3" value={items[key]?.[field]||''} onChange={e=>setItems({...items,[key]:{...items[key],[field]:e.target.value}})}/></label>
 return <main className="min-h-screen bg-[#f6f3ee] p-5 md:p-10"><div className="mx-auto max-w-5xl"><div className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="font-serif text-4xl">Panel de María</h1><p className="text-sm text-black/60">{session.user.email}</p></div><button className="rounded border px-4 py-2" onClick={()=>{localStorage.removeItem('maria_admin_session');setSession(null)}}>Cerrar sesión</button></div><div className="my-8 flex gap-2"><button onClick={()=>setTab('contenido')} className="rounded bg-white px-4 py-2 shadow">Contenido</button><button onClick={()=>setTab('imagenes')} className="rounded bg-white px-4 py-2 shadow">Imágenes</button><button onClick={()=>setTab('avanzado')} className="rounded bg-white px-4 py-2 shadow">Editor avanzado</button></div>{msg&&<div className="mb-5 rounded bg-white p-4 text-sm shadow">{msg}</div>}
 {tab==='contenido'&&<div className="grid gap-6"><section className="rounded-xl bg-white p-6 shadow"><h2 className="mb-5 text-xl font-bold">Portada</h2><div className="grid gap-4">{edit('home.hero','title','Título principal')}{edit('home.hero','subtitle','Texto de portada')}<button onClick={()=>save('home.hero')} className="justify-self-start rounded bg-black px-5 py-2 text-white">Guardar portada</button></div></section><section className="rounded-xl bg-white p-6 shadow"><h2 className="mb-5 text-xl font-bold">Sobre María</h2>{edit('sobre.maria','title','Título')} {edit('sobre.maria','image','URL de imagen')}<button onClick={()=>save('sobre.maria')} className="mt-4 rounded bg-black px-5 py-2 text-white">Guardar</button></section><section className="rounded-xl bg-white p-6 shadow"><h2 className="mb-5 text-xl font-bold">Contacto</h2>{edit('contacto','email','Email')}{edit('contacto','whatsapp','WhatsApp')}<button onClick={()=>save('contacto')} className="mt-4 rounded bg-black px-5 py-2 text-white">Guardar</button></section></div>}
 {tab==='imagenes'&&<section className="rounded-xl bg-white p-6 shadow"><h2 className="text-xl font-bold">Subir una imagen</h2><p className="my-3 text-sm text-black/60">La imagen queda guardada de forma permanente. Al subirla se copia su URL para pegarla en el campo de imagen que quieras cambiar.</p><input type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></section>}
 {tab==='avanzado'&&<section className="rounded-xl bg-white p-6 shadow"><h2 className="text-xl font-bold">Editor avanzado</h2><p className="my-3 text-sm text-black/60">Permite crear o modificar bloques de contenido adicionales sin tocar GitHub. Escribe una clave (por ejemplo: meditaciones.cabecera) y su JSON.</p><Advanced session={session} onMsg={setMsg}/></section>}
 </div></main>
}
function Advanced({session,onMsg}:{session:Session,onMsg:(s:string)=>void}){const[k,setK]=useState(''),[v,setV]=useState('{}');async function go(){try{JSON.parse(v);const r=await fetch(`${CMS_URL}/rest/v1/site_content?on_conflict=key`,{method:'POST',headers:{apikey:CMS_KEY,Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({key:k,value:JSON.parse(v)})});if(!r.ok)throw new Error(await r.text());onMsg('Bloque avanzado guardado.')}catch(e:any){onMsg(e.message)}}return <div className="grid gap-3"><input className="rounded border p-3" placeholder="clave" value={k} onChange={e=>setK(e.target.value)}/><textarea className="min-h-64 rounded border p-3 font-mono text-sm" value={v} onChange={e=>setV(e.target.value)}/><button onClick={go} className="justify-self-start rounded bg-black px-5 py-2 text-white">Guardar bloque</button></div>}
