'use client'
import { useEffect, useState } from 'react'
import { CMS_URL, CMS_KEY, CMS_ADMINS } from '@/lib/cms-config'

type Session={access_token:string,user:{email?:string}}
const defaults:any={
 'home.hero':{title:'El sentido de la vida se encuentra sirviendo a la vida',subtitle:'Espiritualidad, conciencia y transformación interior. Una invitación a reconocer aquello que ya somos.'},
 'sobre.maria':{title:'La vida es un despertar',image:'/images/maria-sobre-bn.png',text:'La vida es un despertar. Seamos todos bienvenidos al despertar.\n\nY podemos decirlo sin miedo a equivocarnos: todos estamos sujetos a infinitos despertares al Ser que somos, visto desde esta experiencia procesal llamada vida.\n\nTodo movimiento que toma nuestra vida nos lleva a asumir más amor. Cada cambio es una oportunidad para amar y para amarnos.\n\nAhora puedo decir que el camino del espíritu es un camino de Amor. No necesitas un gurú, o un maestro iluminado; el despertar ya está siendo y sucediendo en ti.\n\nEs la vida misma la que se está ocupando de tu despertar. Poco tienes que hacer. La vida misma te convoca, una y otra vez, a ser la vida que eres.\n\nMi proceso de despertar me ha traído hasta aquí: comunicar lo que somos es dar lo que recibes. Porque nada es para ti, eres canal para la vida. Eres vida.'},
 'youtube.page':{intro1:'La verdad no puede ser pensada. El amor no es un concepto, no es algo personal que alguien pueda darte. El amor se conoce siéndolo.',intro2:'El Despertar es un canal de YouTube dedicado a la espiritualidad, la conciencia y la transformación interior.',intro3:'Es un canal para personas que sienten una llamada interior, que buscan comprender el sentido profundo de lo que viven.',deepeningTitle:'Vídeos para profundizar',deepeningText:'Únete a estos vídeos desde el sentir, soltando por un instante la necesidad de entender desde la mente.',archiveTitle:'Entrevistas para el Despertar',archiveText:'Conversaciones que nos invitan a mirar hacia dentro, cuestionar lo que creemos saber y abrirnos al sentir.',deepeningIds:['U03rxJJt5p4','TsLISNp5FhE','bIvkCRVOnqs','ELPK5AA7Epw','jMi5r7K2DQM']},
 'meditaciones.page':{title:'Meditamos para despertar',intro:'Meditar es una forma de vivir. No meditamos para relajarnos o para no pensar, meditamos para despertar.',image:'/images/maria-meditaciones-primer-plano.jpg',esTitle:'Meditaciones en castellano',caTitle:'Meditaciones en catalán',audiobookTitle:'Audiolibro',esIds:['l5l-q-m_5iQ','oLnOtb766ow','LBqjk2hZnIk','d8x82zo4AV8','3reM-aPW4AU','_9mEMZJlH-8','4vuOl5WJ_XA','ygjCVb0mURs','0006X14bPyE','6676RZILFGo','UfF0JTr1ygw','OL7rYjzFob4'],caIds:['ZZNtMh0iRIc','imVkMAQ_1YA','ym93FpHhS_g','T_lqkdgf1Lo','xx7K9cewXDw']},
 'agenda.page':{title:'Encuentros para el despertar',intro:'Espacios presenciales y mensuales para compartir desde el Ser, contemplar y abrirnos juntos al amor.'},
 'agenda.events':[{id:'ev-1',title:'Experimento Rendición',description:'Encuentro mensual. Empieza el 1 de octubre. El primer jueves de cada mes, de 19:30 a 21:30. Compartir desde el Ser.',meta:'Encuentro mensual · Primer jueves de mes · 19:30–21:30',price:'Trimestre: 60 €',image:'/images/evento-experimento-rendicion-octubre-2026.png'},{id:'ev-2',title:'Próximo retiro del Despertar',description:'Conciencia y Ego · con Nuria Guinart y María Olid. Delta del Ebro · Hotel Carlos III, Alcanar · 14 y 15 de noviembre de 2026.',meta:'Retiro · 14 y 15 de noviembre de 2026',price:'',image:'/images/evento-retiro-despertar-noviembre-2026.png'}],
 'acompanamiento.page':{image:'/images/acompanamiento-acoger-la-vida.png',quote:'“Acoger la Vida, acompañando la vida”',author:'María Olid',subtitle:'Un espacio de acompañamiento espiritual y claridad interior para la vida diaria.',ctaTitle:'¿Sientes el llamado a mirar dentro?',ctaText:'Solicita un espacio de acompañamiento individual y nos pondremos en contacto contigo para coordinarlo.'},
 'contacto.page':{title:'Escríbeme',intro:'Si sientes el llamado a compartir, preguntar o acompañarte, escríbeme. Con gusto te responderé.',boxTitle:'Hablemos',boxText:'Comunicar lo que somos es dar lo que recibes. Estaré encantada de escucharte.',email:'olid.maria@gmail.com',whatsapp:'https://wa.me/34620430048'},
}
async function req(path:string,init:any={}){const r=await fetch(CMS_URL+path,{...init,headers:{apikey:CMS_KEY,'Content-Type':'application/json',...(init.headers||{})}});if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json()}
export default function Admin(){
 const [session,setSession]=useState<Session|null>(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[msg,setMsg]=useState(''),[items,setItems]=useState<any>(defaults),[page,setPage]=useState('inicio')
 useEffect(()=>{const s=localStorage.getItem('maria_admin_session');if(s)setSession(JSON.parse(s))},[]); useEffect(()=>{if(session)load()},[session])
 async function login(signup=false){try{setMsg('');if(password.length<6)throw new Error('La contraseña debe tener al menos 6 caracteres.');if(!CMS_ADMINS.includes(email.toLowerCase()))throw new Error('Este correo no está autorizado.');const p=signup?'/auth/v1/signup':'/auth/v1/token?grant_type=password';const d=await req(p,{method:'POST',body:JSON.stringify({email,password})});if(!d.access_token){setMsg('Cuenta creada. Si recibes un correo de confirmación, confírmalo y después pulsa Entrar.');return}localStorage.setItem('maria_admin_session',JSON.stringify(d));setSession(d)}catch(e:any){setMsg(e.message)}}
 async function load(){try{const d=await req('/rest/v1/site_content?select=key,value',{headers:{Authorization:`Bearer ${session!.access_token}`}});const n=structuredClone(defaults);d.forEach((x:any)=>n[x.key]=x.value);setItems(n)}catch(e:any){setMsg(e.message)}}
 async function save(key:string){try{await req('/rest/v1/site_content?on_conflict=key',{method:'POST',headers:{Authorization:`Bearer ${session!.access_token}`,Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({key,value:items[key]})});setMsg('✓ Cambios guardados. Recarga la página pública para verlos.')}catch(e:any){setMsg(e.message)}}
 async function upload(file:File,key?:string,field?:string){try{const safe=Date.now()+'-'+file.name.replace(/[^a-zA-Z0-9._-]/g,'-');const r=await fetch(`${CMS_URL}/storage/v1/object/site-media/${safe}`,{method:'POST',headers:{apikey:CMS_KEY,Authorization:`Bearer ${session!.access_token}`,'Content-Type':file.type},body:file});if(!r.ok)throw new Error(await r.text());const url=`${CMS_URL}/storage/v1/object/public/site-media/${safe}`;if(key&&field)setItems((x:any)=>({...x,[key]:{...x[key],[field]:url}}));setMsg('✓ Imagen subida. Pulsa Guardar para publicarla.')}catch(e:any){setMsg(e.message)}}
 const set=(key:string,field:string,value:any)=>setItems((x:any)=>({...x,[key]:{...x[key],[field]:value}}));
 const Field=({k,f,label,rows=2}:{k:string,f:string,label:string,rows?:number})=><label className="block"><b className="mb-1 block text-sm">{label}</b><textarea rows={rows} className="w-full rounded border p-3" value={items[k]?.[f]||''} onChange={e=>set(k,f,e.target.value)}/></label>
 const ImageField=({k,f,label}:{k:string,f:string,label:string})=><div><b className="mb-1 block text-sm">{label}</b><input className="w-full rounded border p-3 text-sm" value={items[k]?.[f]||''} onChange={e=>set(k,f,e.target.value)}/><input className="mt-2 text-sm" type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],k,f)}/></div>
 const Card=({title,k,children}:{title:string,k:string,children:any})=><section className="rounded-xl bg-white p-5 shadow"><h2 className="mb-5 font-serif text-2xl">{title}</h2><div className="grid gap-4">{children}<button onClick={()=>save(k)} className="justify-self-start rounded bg-black px-5 py-2 text-white">Guardar cambios</button></div></section>
 if(!session)return <main className="min-h-screen bg-[#f6f3ee] px-5 py-20"><div className="mx-auto max-w-md rounded-xl bg-white p-8 shadow-xl"><h1 className="font-serif text-3xl">Gestión · El Despertar</h1><p className="mt-2 text-sm text-black/60">Panel privado.</p><input className="mt-8 w-full rounded border p-3" placeholder="Correo autorizado" value={email} onChange={e=>setEmail(e.target.value)}/><input className="mt-3 w-full rounded border p-3" type="password" placeholder="Contraseña (mínimo 6 caracteres)" value={password} onChange={e=>setPassword(e.target.value)}/><button onClick={()=>login(false)} className="mt-5 w-full rounded bg-black p-3 text-white">Entrar</button><button onClick={()=>login(true)} className="mt-3 w-full rounded border p-3">Crear mi acceso por primera vez</button>{msg&&<p className="mt-4 whitespace-pre-wrap text-sm">{msg}</p>}</div></main>
 const nav=[['inicio','Inicio'],['sobre','Sobre María'],['youtube','Entrevistas'],['meditaciones','Meditaciones'],['agenda','Agenda / Eventos'],['acompanamiento','Acompañamiento'],['contacto','Contacto']]
 return <main className="min-h-screen bg-[#f6f3ee] p-4 md:p-8"><div className="mx-auto max-w-7xl"><header className="mb-6 flex items-center justify-between"><div><h1 className="font-serif text-3xl md:text-4xl">Panel de María</h1><p className="text-sm text-black/55">Edita la web sin tocar GitHub</p></div><button className="rounded border px-3 py-2" onClick={()=>{localStorage.removeItem('maria_admin_session');setSession(null)}}>Salir</button></header><div className="grid gap-6 md:grid-cols-[220px_1fr]"><aside className="h-fit rounded-xl bg-white p-3 shadow md:sticky md:top-4">{nav.map(([id,l])=><button key={id} onClick={()=>{setPage(id);setMsg('')}} className={`mb-1 w-full rounded px-3 py-2 text-left text-sm ${page===id?'bg-black text-white':'hover:bg-black/5'}`}>{l}</button>)}</aside><div>{msg&&<div className="mb-5 rounded bg-white p-4 text-sm shadow">{msg}</div>}<div className="grid gap-6">
 {page==='inicio'&&<Card title="Página de inicio" k="home.hero"><Field k="home.hero" f="title" label="Título principal"/><Field k="home.hero" f="subtitle" label="Texto debajo del título" rows={4}/><p className="text-sm text-black/55">El bloque “Último vídeo” permanece automático desde YouTube para no romper la integración.</p></Card>}
 {page==='sobre'&&<Card title="Sobre María" k="sobre.maria"><Field k="sobre.maria" f="title" label="Título"/><ImageField k="sobre.maria" f="image" label="Foto de María"/><Field k="sobre.maria" f="text" label="Texto completo (separa párrafos con una línea en blanco)" rows={16}/></Card>}
 {page==='youtube'&&<Card title="Entrevistas / YouTube" k="youtube.page"><Field k="youtube.page" f="intro1" label="Texto introductorio 1" rows={5}/><Field k="youtube.page" f="intro2" label="Texto introductorio 2" rows={5}/><Field k="youtube.page" f="intro3" label="Texto introductorio 3" rows={4}/><Field k="youtube.page" f="deepeningTitle" label="Título Vídeos para profundizar"/><Field k="youtube.page" f="deepeningText" label="Texto de Vídeos para profundizar" rows={3}/><label><b className="mb-1 block text-sm">IDs de vídeos para profundizar (uno por línea)</b><textarea rows={7} className="w-full rounded border p-3 font-mono text-sm" value={(items['youtube.page'].deepeningIds||[]).join('\n')} onChange={e=>set('youtube.page','deepeningIds',e.target.value.split(/\n+/).map(x=>x.trim()).filter(Boolean))}/></label><Field k="youtube.page" f="archiveTitle" label="Título archivo de entrevistas"/><Field k="youtube.page" f="archiveText" label="Texto archivo de entrevistas" rows={3}/></Card>}
 {page==='meditaciones'&&<Card title="Meditaciones" k="meditaciones.page"><Field k="meditaciones.page" f="title" label="Título principal"/><Field k="meditaciones.page" f="intro" label="Texto principal" rows={6}/><ImageField k="meditaciones.page" f="image" label="Imagen de cabecera"/><Field k="meditaciones.page" f="esTitle" label="Título castellano"/><label><b className="text-sm">IDs YouTube castellano (uno por línea)</b><textarea rows={10} className="mt-1 w-full rounded border p-3 font-mono text-sm" value={(items['meditaciones.page'].esIds||[]).join('\n')} onChange={e=>set('meditaciones.page','esIds',e.target.value.split(/\n+/).map(x=>x.trim()).filter(Boolean))}/></label><Field k="meditaciones.page" f="caTitle" label="Título catalán"/><label><b className="text-sm">IDs YouTube catalán (uno por línea)</b><textarea rows={7} className="mt-1 w-full rounded border p-3 font-mono text-sm" value={(items['meditaciones.page'].caIds||[]).join('\n')} onChange={e=>set('meditaciones.page','caIds',e.target.value.split(/\n+/).map(x=>x.trim()).filter(Boolean))}/></label><Field k="meditaciones.page" f="audiobookTitle" label="Título audiolibro"/></Card>}
 {page==='agenda'&&<><Card title="Cabecera de Agenda" k="agenda.page"><Field k="agenda.page" f="title" label="Título"/><Field k="agenda.page" f="intro" label="Texto" rows={4}/></Card><Events items={items} setItems={setItems} save={save} upload={upload}/></>}
 {page==='acompanamiento'&&<Card title="Acompañamiento" k="acompanamiento.page"><ImageField k="acompanamiento.page" f="image" label="Imagen principal"/><Field k="acompanamiento.page" f="quote" label="Frase principal"/><Field k="acompanamiento.page" f="author" label="Firma"/><Field k="acompanamiento.page" f="subtitle" label="Subtítulo" rows={4}/><Field k="acompanamiento.page" f="ctaTitle" label="Título llamada final"/><Field k="acompanamiento.page" f="ctaText" label="Texto llamada final" rows={3}/></Card>}
 {page==='contacto'&&<Card title="Contacto" k="contacto.page"><Field k="contacto.page" f="title" label="Título"/><Field k="contacto.page" f="intro" label="Introducción" rows={4}/><Field k="contacto.page" f="boxTitle" label="Título del bloque"/><Field k="contacto.page" f="boxText" label="Texto del bloque" rows={3}/><Field k="contacto.page" f="email" label="Email"/><Field k="contacto.page" f="whatsapp" label="Enlace de WhatsApp"/></Card>}
 </div></div></div></div></main>
}
function Events({items,setItems,save,upload}:any){const ev=items['agenda.events']||[];const change=(i:number,f:string,v:string)=>{const a=ev.map((x:any,j:number)=>j===i?{...x,[f]:v}:x);setItems((z:any)=>({...z,'agenda.events':a}))};return <section className="rounded-xl bg-white p-5 shadow"><div className="mb-5 flex items-center justify-between"><h2 className="font-serif text-2xl">Próximos eventos</h2><button className="rounded border px-3 py-2 text-sm" onClick={()=>setItems((z:any)=>({...z,'agenda.events':[...ev,{id:'ev-'+Date.now(),title:'Nuevo evento',description:'',meta:'',price:'',image:''}]}))}>+ Añadir evento</button></div><div className="grid gap-6">{ev.map((e:any,i:number)=><div key={e.id} className="rounded border p-4"><div className="grid gap-3"><input className="rounded border p-3" value={e.title} onChange={x=>change(i,'title',x.target.value)} placeholder="Título"/><textarea className="rounded border p-3" rows={4} value={e.description} onChange={x=>change(i,'description',x.target.value)} placeholder="Descripción"/><input className="rounded border p-3" value={e.meta} onChange={x=>change(i,'meta',x.target.value)} placeholder="Fecha / información breve"/><input className="rounded border p-3" value={e.price||''} onChange={x=>change(i,'price',x.target.value)} placeholder="Precio (opcional)"/><input className="rounded border p-3 text-sm" value={e.image||''} onChange={x=>change(i,'image',x.target.value)} placeholder="URL imagen"/><input type="file" accept="image/*" onChange={async x=>{const f=x.target.files?.[0];if(!f)return;const safe=Date.now()+'-'+f.name.replace(/[^a-zA-Z0-9._-]/g,'-');const r=await fetch(`${CMS_URL}/storage/v1/object/site-media/${safe}`,{method:'POST',headers:{apikey:CMS_KEY,Authorization:`Bearer ${JSON.parse(localStorage.getItem('maria_admin_session')||'{}').access_token}`,'Content-Type':f.type},body:f});if(r.ok)change(i,'image',`${CMS_URL}/storage/v1/object/public/site-media/${safe}`)}}/><button className="justify-self-start text-sm text-red-700" onClick={()=>setItems((z:any)=>({...z,'agenda.events':ev.filter((_:any,j:number)=>j!==i)}))}>Eliminar evento</button></div></div>)}<button onClick={()=>save('agenda.events')} className="justify-self-start rounded bg-black px-5 py-2 text-white">Guardar todos los eventos</button></div></section>}
